### ISSUE TITLE
Regarding night image

### ISSUE THREAD

**Issue by mreece813** [arunnthevapalan/day-night-classifier#1]
Hello. i came across this code and thought it looked interesting and i wanted to try and see how it would look on detecting night images. i have tried to do the display of the images and the classification of the images. every time i run the code piece i get the same images. is there a way to get a random images. this is the part of the code i am talking about:
![image](https://user-images.githubusercontent.com/29603698/164527539-b6f0bc9f-d6a0-485e-9ea9-27bf337f5f1d.png)

**Comment by arunnthevapalan** [comment]
Hey - yes you can do it. Simply change the `image_num` variable to different numbers within the range of images (say `image_num = 5`, and you should be able to display different images. Sorry if that wasn't clear. I hope this helps! :)
